version: '3.7'

services:
  api:
    container_name: menu_api
    build:
      context: .
      network: host
    ports:
      - "8888:8000"
    volumes:
      - .:/code
    restart: always
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - POSTGRES_HOST=ra_db_menu
      - POSTGRES_PORT=5432
    env_file:
      - src/config/.env
    depends_on:
      - postgres

  postgres:
    container_name: ra_db_menu
    hostname: ra_menu_host
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    env_file:
      - src/config/.env

volumes:
  postgres_data:
