version: '3.7'

services:
  web:
    container_name: web_nginx
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./src/config/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  api:
    container_name: menu_api
    build:
      context: .
      network: host
    ports:
      - "8888:8000"
    volumes:
      - .:/code
    restart: always
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - POSTGRES_HOST=ra_db_menu
      - POSTGRES_PORT=5432
    env_file:
      - src/config/.env
    depends_on:
      - postgres
    networks:
      - custom

  postgres:
    container_name: ra_db_menu
    hostname: ra_menu_host
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    env_file:
      - src/config/.env
    networks:
      - custom

volumes:
  postgres_data:
networks:
  custom:
    driver: bridge