"""init

Revision ID: 326cab64a71b
Revises: 478d54451d7a
Create Date: 2023-09-16 15:37:34.373361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326cab64a71b'
down_revision = '478d54451d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
